"""
pdf_export.py -- Export negotiation scorecard as PDF using fpdf2.

Generates a "Negotiation Cheat Sheet & Scorecard" PDF that the user can
take into their real supplier conversation.
"""

import os
import sys
from datetime import datetime
from fpdf import FPDF
from fpdf.enums import XPos, YPos

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


class NegotiationPDF(FPDF):
    """Custom FPDF subclass with header/footer."""

    def header(self):
        # Fix #1: Use DejaVu (Unicode font) so characters like rupee symbol,
        # bullet points, and any user-supplied text render without crashing.
        self.set_font("DejaVu", "B", 14)
        self.set_fill_color(30, 64, 175)  # Dark blue
        self.set_text_color(255, 255, 255)
        # Use plain hyphen instead of em dash (safer across all font encodings)
        self.cell(0, 12, "NegotiatorAI - Negotiation Cheat Sheet", new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font("DejaVu", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Generated by NegotiatorAI | {datetime.now().strftime('%Y-%m-%d %H:%M')} | Page {self.page_no()}", align="C")


def _section_header(pdf: FPDF, title: str):
    """Add a styled section header."""
    pdf.set_fill_color(219, 234, 254)  # Light blue
    pdf.set_font("DejaVu", "B", 11)
    pdf.cell(0, 8, f"  {title}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
    pdf.ln(1)


def _kv_row(pdf: FPDF, key: str, value: str):
    """Add a key-value row."""
    pdf.set_font("DejaVu", "B", 10)
    pdf.cell(55, 6, key + ":", new_x=XPos.RIGHT)
    pdf.set_font("DejaVu", "", 10)
    pdf.multi_cell(0, 6, str(value), new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def _bullet_list(pdf: FPDF, items: list):
    """Add a bullet list."""
    pdf.set_font("DejaVu", "", 10)
    for item in items:
        pdf.cell(8, 6, "\u2022", new_x=XPos.RIGHT)
        pdf.multi_cell(0, 6, str(item), new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def _score_bar(pdf: FPDF, label: str, score: float, max_score: float = 5.0):
    """Add a score label + visual bar."""
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(60, 6, label + ":", new_x=XPos.RIGHT)

    bar_w = 80
    filled = int((score / max_score) * bar_w)
    # Background bar
    pdf.set_fill_color(220, 220, 220)
    pdf.rect(pdf.get_x(), pdf.get_y() + 1, bar_w, 4, style="F")
    # Filled bar
    color = (34, 197, 94) if score >= 4 else (251, 191, 36) if score >= 3 else (239, 68, 68)
    pdf.set_fill_color(*color)
    pdf.rect(pdf.get_x(), pdf.get_y() + 1, filled, 4, style="F")
    pdf.set_x(pdf.get_x() + bar_w + 3)
    pdf.cell(20, 6, f"{score:.1f}/5", new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def generate_scorecard_pdf(
    state: dict,
    output_path: str = None,
) -> bytes:
    """
    Generate a negotiation cheat sheet + scorecard PDF.

    Args:
        state: The NegotiationState dict containing deal_facts, hitl_edited,
               scorecard, analyst_summary, etc.
        output_path: Optional file path to save the PDF

    Returns:
        PDF as bytes (for Streamlit download button)
    """
    deal = state.get("deal_facts", {})
    hitl = state.get("hitl_edited") or state.get("strategist_draft", {})
    scorecard = state.get("scorecard", {})
    analyst = state.get("analyst_summary", "")
    business_name = state.get("business_name", "Your Business")
    rag_mode = state.get("rag_mode", "agentic_rag")

    # Parse analyst summary if JSON string
    import json
    if isinstance(analyst, str):
        try:
            analyst_data = json.loads(analyst)
        except Exception:
            analyst_data = {"analyst_summary": analyst}
    else:
        analyst_data = analyst or {}

    pdf = NegotiationPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Fix #1: Register DejaVu Unicode font so any character (rupee, bullets,
    # em dashes in user text, etc.) renders without a Latin-1 encoding crash.
    # fpdf2 bundles DejaVu fonts; no external file needed.
    pdf.add_font("DejaVu", "", "DejaVuSansCondensed.ttf", uni=True)
    pdf.add_font("DejaVu", "B", "DejaVuSansCondensed-Bold.ttf", uni=True)
    pdf.add_font("DejaVu", "I", "DejaVuSansCondensed-Oblique.ttf", uni=True)

    pdf.add_page()
    pdf.set_margins(15, 15, 15)

    # -----------------------------------------------------------------------
    # Title block
    # -----------------------------------------------------------------------
    pdf.set_font("DejaVu", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 5, f"Business: {business_name}  |  Date: {datetime.now().strftime('%Y-%m-%d')}  |  Mode: {rag_mode.replace('_', ' ').title()}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # -----------------------------------------------------------------------
    # Section 1: Deal Summary
    # -----------------------------------------------------------------------
    _section_header(pdf, "1. Deal Summary")
    _kv_row(pdf, "Item", deal.get("item", "N/A"))
    _kv_row(pdf, "Quantity", deal.get("quantity", "N/A"))
    _kv_row(pdf, "Supplier", deal.get("supplier_name", "Not specified"))
    _kv_row(pdf, "Quoted Price", f"{deal.get('quoted_price', 'N/A')} {deal.get('quoted_price_unit', '')}")
    _kv_row(pdf, "Quoted Terms", deal.get("payment_terms", "N/A"))
    pdf.ln(3)

    # -----------------------------------------------------------------------
    # Section 2: Your Counter-Offer Strategy
    # -----------------------------------------------------------------------
    _section_header(pdf, "2. Your Counter-Offer Strategy")
    counter_pct = hitl.get("counter_offer_pct", 0)
    counter_amt = hitl.get("counter_offer_amount", 0)
    discount_pct = 100 - counter_pct
    _kv_row(pdf, "Target Counter-Offer", f"{counter_amt} {deal.get('quoted_price_unit', '')}  ({discount_pct:.1f}% discount)")

    primary_tactic = hitl.get("primary_tactic", "")
    if primary_tactic:
        _kv_row(pdf, "Primary Tactic", primary_tactic)

    alt_asks = hitl.get("alt_asks", [])
    if alt_asks:
        pdf.set_font("DejaVu", "B", 10)
        pdf.cell(0, 6, "Alternative Asks:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        _bullet_list(pdf, alt_asks)
    pdf.ln(3)

    # -----------------------------------------------------------------------
    # Section 3: Your Leverage Points
    # -----------------------------------------------------------------------
    _section_header(pdf, "3. Your Leverage Points (Use These!)")
    leverage = hitl.get("leverage_points", [])
    if leverage:
        _bullet_list(pdf, leverage)
    else:
        pdf.set_font("DejaVu", "I", 10)
        pdf.cell(0, 6, "No leverage points specified.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # -----------------------------------------------------------------------
    # Section 4: Opening Script
    # -----------------------------------------------------------------------
    _section_header(pdf, "4. Opening Script (Use Verbatim or Adapt)")
    script = hitl.get("opening_script", "")
    if script:
        pdf.set_font("DejaVu", "I", 10)
        pdf.set_fill_color(248, 250, 252)
        pdf.multi_cell(0, 6, f'"{script}"', fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # -----------------------------------------------------------------------
    # Section 5: Evidence Summary (from Analyst)
    # -----------------------------------------------------------------------
    _section_header(pdf, "5. Evidence Summary (from Knowledge Base)")
    evidence_str = analyst_data.get("analyst_summary", "No evidence retrieved.")
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5, evidence_str[:800], new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    benchmarks = analyst_data.get("relevant_benchmarks", [])
    if benchmarks:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Key Benchmarks:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        _bullet_list(pdf, benchmarks[:5])
    pdf.ln(3)

    # -----------------------------------------------------------------------
    # Section 6: Rehearsal Scorecard
    # -----------------------------------------------------------------------
    if scorecard and scorecard.get("overall_score", 0) > 0:
        pdf.add_page()
        _section_header(pdf, "6. Rehearsal Scorecard")
        _score_bar(pdf, "Overall", scorecard.get("overall_score", 0))
        _score_bar(pdf, "Assertiveness", scorecard.get("assertiveness", 0))
        _score_bar(pdf, "Leverage Use", scorecard.get("leverage_use", 0))
        _score_bar(pdf, "Pushback Handling", scorecard.get("pushback_handling", 0))
        _score_bar(pdf, "Closing Technique", scorecard.get("closing_technique", 0))
        pdf.ln(3)

        coaching = scorecard.get("coaching_notes", "")
        if coaching:
            _kv_row(pdf, "Coach Notes", coaching)

        strengths = scorecard.get("strengths", [])
        if strengths:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Strengths:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            _bullet_list(pdf, strengths)

        improvements = scorecard.get("improvements", [])
        if improvements:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Areas to Improve:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            _bullet_list(pdf, improvements)
        pdf.ln(3)

        final_script = scorecard.get("final_script", "")
        if final_script:
            _section_header(pdf, "7. Improved Opening Script (Post-Coaching)")
            pdf.set_font("Helvetica", "I", 10)
            pdf.set_fill_color(248, 250, 252)
            pdf.multi_cell(0, 6, f'"{final_script}"', fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # -----------------------------------------------------------------------
    # Section 7: Known Limitation Notice
    # -----------------------------------------------------------------------
    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(128, 128, 128)
    limitation = (
        "Note: Recommendations are based on user-supplied deal facts and curated negotiation knowledge. "
        "NegotiatorAI does not independently verify market prices across all item categories — "
        "this is a deliberate scope trade-off (cross-industry generality over deep price-accuracy). "
        "Supplement with your own market research for best results."
    )
    pdf.multi_cell(0, 4, limitation, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # -----------------------------------------------------------------------
    # Output
    # -----------------------------------------------------------------------
    pdf_bytes = bytes(pdf.output())

    if output_path:
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)

    return pdf_bytes
